version: '3.8'
services:
  pythonAPI:
    image: python-with-flask
    ports:
      - "8000:5000"
    restart: always
  redis:
    depends_on:
      - pythonAPI
    image: redis
    ports:
      - '6379:6379'
    volumes: 
      - ./cache:/data
    restart: always
volumes:
  cache:
    driver: local