# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    volumes:
      - C:\Users\017924631\Docker\postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    
  volumes:
    db-data:
    driver: local

